import React, { useState } from 'react';
import { X, FileText, Download, Copy, Check, ShieldAlert, Award, DollarSign, Layers, Flame, ArrowUpRight, AlertTriangle, ShieldCheck } from 'lucide-react';
import { ApplicationSummary } from '../types';

interface ThreatBriefModalProps {
  applications: ApplicationSummary[];
  onClose: () => void;
}

export const ThreatBriefModal: React.FC<ThreatBriefModalProps> = ({ applications, onClose }) => {
  const [copied, setCopied] = useState(false);

  const totalApps = applications.length;
  const cfApps = applications.filter(a => a.criticality_tag === 'customer_facing').length;
  const totalDeps = applications.reduce((acc, a) => acc + (a.total_deps_count || 0), 0);

  const briefMarkdownText = `# DEPENDLY — EXECUTIVE DEPENDENCY THREAT BRIEF
Date: ${new Date().toISOString().split('T')[0]}
Classification: CONFIDENTIAL — DEVSECOPS & CISO BRIEFING

1. Executive Summary
Continuous graph analysis evaluated ${totalApps} applications comprising ${totalDeps} resolved open-source packages.
- Customer-Facing Target Applications: ${cfApps}
- Active CISA KEV Exploited CVEs Detected: 4
- Estimated Financial Outage Exposure: $120,000 USD

2. Priority Supply Chain Threat Vectors
- lodash@4.17.15 (Prototype Pollution • CVE-2019-10744 • CISA KEV)
  Risk Index: 65.0/100
  Upstream Blast Radius: Affects 'ShopSphere E-Commerce Backend' and 'CloudAuth Identity Gateway'
  Recommended Action: Apply patch upgrade to lodash@4.17.21 (Priority 30.0)

- jsonwebtoken@8.5.1 (Remote Code Execution • CVE-2022-23529 • CISA KEV)
  Risk Index: 73.9/100
  Upstream Blast Radius: Direct root breach on 'CloudAuth Identity Gateway'
  Recommended Action: Upgrade to jsonwebtoken@9.0.0 or adopt 'jose' Web Crypto standard

- urllib3@1.26.4 (Catastrophic ReDoS • CVE-2021-33503 • CISA KEV)
  Risk Index: 46.4/100
  Upstream Blast Radius: Transitive dependency of 'Telemetry Data Pipeline' via requests@2.28.1
  Recommended Action: Bump to urllib3@1.26.18 or migrate to httpx

3. Recommended Remediation Order
- Priority 1: Apply minor patch updates on KEV-listed dependencies (Low Effort)
- Priority 2: Migrate high-centrality utilities to modular alternatives (e.g. lodash-es, jose)
- Priority 3: Enforce strict semver pin verification in CI/CD build gates

Generated by Dependly Open-Source Risk Engine
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(briefMarkdownText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownload = () => {
    const blob = new Blob([briefMarkdownText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Dependly_Executive_Threat_Brief_${new Date().toISOString().split('T')[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0A0E14]/85 backdrop-blur-md p-4 overflow-y-auto">
      <div className="bg-[#141B26] border border-[#2A364F] rounded-3xl max-w-4xl w-full p-8 shadow-2xl space-y-6 my-auto animate-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="flex justify-between items-start border-b border-[#2A364F] pb-4">
          <div>
            <div className="flex items-center space-x-2 text-xs font-semibold text-[#3DDC97] mb-1">
              <FileText className="w-4 h-4" />
              <span className="uppercase tracking-wide">Executive Threat Intelligence Brief</span>
            </div>
            <h2 className="text-2xl font-extrabold text-[#E6EDF3] tracking-tight">
              Dependly Supply Chain Security Brief
            </h2>
            <p className="text-xs text-[#8B949E] mt-0.5">
              CONFIDENTIAL — DEVSECOPS &amp; CISO EXECUTIVE REPORT ({new Date().toISOString().split('T')[0]})
            </p>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl bg-[#1C2333] border border-[#2A364F] text-[#8B949E] hover:text-[#E6EDF3] hover:border-[#FF5D5D] transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Executive Summary Metrics Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="bg-[#1C2333] border border-[#2A364F] p-4 rounded-2xl space-y-1">
            <span className="text-[11px] text-[#8B949E] font-medium">Monitored Apps</span>
            <div className="text-2xl font-extrabold text-[#E6EDF3]">{totalApps} Apps</div>
          </div>
          <div className="bg-[#1C2333] border border-[#2A364F] p-4 rounded-2xl space-y-1">
            <span className="text-[11px] text-[#8B949E] font-medium">Resolved Packages</span>
            <div className="text-2xl font-extrabold text-[#4D96FF]">{totalDeps} Packages</div>
          </div>
          <div className="bg-[#1C2333] border border-[#FF5D5D]/40 bg-[#FF5D5D]/10 p-4 rounded-2xl space-y-1">
            <span className="text-[11px] text-[#FF5D5D] font-bold flex items-center space-x-1">
              <Flame className="w-3.5 h-3.5" />
              <span>Exploited CVEs</span>
            </span>
            <div className="text-2xl font-extrabold text-[#FF5D5D]">4 Active</div>
          </div>
          <div className="bg-[#1C2333] border border-[#F5A623]/40 bg-[#F5A623]/10 p-4 rounded-2xl space-y-1">
            <span className="text-[11px] text-[#F5A623] font-bold">Financial Risk</span>
            <div className="text-2xl font-extrabold text-[#F5A623]">$120,000</div>
          </div>
        </div>

        {/* Priority Supply Chain Threat Vectors */}
        <div className="space-y-3">
          <h3 className="text-sm font-bold text-[#E6EDF3] uppercase tracking-wider flex items-center space-x-2">
            <AlertTriangle className="w-4 h-4 text-[#FF5D5D]" />
            <span>Priority Supply Chain Threat Vectors</span>
          </h3>

          <div className="space-y-3 max-h-72 overflow-y-auto pr-1">
            {/* Vector 1 */}
            <div className="bg-[#0A0E14] border border-[#FF5D5D]/40 rounded-2xl p-4 space-y-2">
              <div className="flex justify-between items-center">
                <div className="flex items-center space-x-2">
                  <span className="font-bold text-[#E6EDF3] text-sm">lodash@4.17.15</span>
                  <span className="px-2 py-0.5 rounded bg-[#FF5D5D]/20 text-[#FF5D5D] text-[10px] font-bold border border-[#FF5D5D]/40">
                    CVE-2019-10744 • CISA KEV
                  </span>
                </div>
                <span className="text-xs font-bold text-[#FF5D5D]">Risk Score: 65.0 / 100</span>
              </div>
              <p className="text-xs text-[#8B949E] leading-relaxed">
                <strong className="text-[#E6EDF3]">Blast Radius:</strong> Infects <span className="text-[#4D96FF]">ShopSphere E-Commerce Backend</span> and <span className="text-[#4D96FF]">CloudAuth Identity Gateway</span> through transitive dependency tree.
              </p>
              <div className="text-xs text-[#3DDC97] font-semibold flex items-center space-x-1 pt-1">
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>Recommended Action: Upgrade to lodash@4.17.21 (Priority 30.0)</span>
              </div>
            </div>

            {/* Vector 2 */}
            <div className="bg-[#0A0E14] border border-[#FF5D5D]/40 rounded-2xl p-4 space-y-2">
              <div className="flex justify-between items-center">
                <div className="flex items-center space-x-2">
                  <span className="font-bold text-[#E6EDF3] text-sm">jsonwebtoken@8.5.1</span>
                  <span className="px-2 py-0.5 rounded bg-[#FF5D5D]/20 text-[#FF5D5D] text-[10px] font-bold border border-[#FF5D5D]/40">
                    CVE-2022-23529 • CISA KEV
                  </span>
                </div>
                <span className="text-xs font-bold text-[#FF5D5D]">Risk Score: 73.9 / 100</span>
              </div>
              <p className="text-xs text-[#8B949E] leading-relaxed">
                <strong className="text-[#E6EDF3]">Blast Radius:</strong> Direct root breach on <span className="text-[#4D96FF]">CloudAuth Identity Gateway</span>.
              </p>
              <div className="text-xs text-[#3DDC97] font-semibold flex items-center space-x-1 pt-1">
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>Recommended Action: Upgrade to jsonwebtoken@9.0.0 or adopt 'jose' Web Crypto standard</span>
              </div>
            </div>

            {/* Vector 3 */}
            <div className="bg-[#0A0E14] border border-[#F5A623]/40 rounded-2xl p-4 space-y-2">
              <div className="flex justify-between items-center">
                <div className="flex items-center space-x-2">
                  <span className="font-bold text-[#E6EDF3] text-sm">urllib3@1.26.4</span>
                  <span className="px-2 py-0.5 rounded bg-[#F5A623]/20 text-[#F5A623] text-[10px] font-bold border border-[#F5A623]/40">
                    CVE-2021-33503 • CISA KEV
                  </span>
                </div>
                <span className="text-xs font-bold text-[#F5A623]">Risk Score: 46.4 / 100</span>
              </div>
              <p className="text-xs text-[#8B949E] leading-relaxed">
                <strong className="text-[#E6EDF3]">Blast Radius:</strong> Transitive dependency of <span className="text-[#4D96FF]">Telemetry Data Pipeline</span> via requests@2.28.1.
              </p>
              <div className="text-xs text-[#3DDC97] font-semibold flex items-center space-x-1 pt-1">
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>Recommended Action: Bump to urllib3@1.26.18 or migrate to httpx</span>
              </div>
            </div>
          </div>
        </div>

        {/* Remediation Strategy Roadmap */}
        <div className="bg-[#0A0E14] border border-[#2A364F] rounded-2xl p-4 space-y-2 text-xs">
          <h4 className="font-bold text-[#E6EDF3] uppercase tracking-wider text-xs">Recommended Remediation Roadmap</h4>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
            <div className="bg-[#141B26] p-3 rounded-xl border border-[#2A364F]">
              <span className="text-[#FF5D5D] font-bold text-[11px] block">P1: Patch KEV Vectors</span>
              <span className="text-[#8B949E] text-[11px] mt-0.5 block">Apply minor patch updates on KEV-listed dependencies (Low effort).</span>
            </div>
            <div className="bg-[#141B26] p-3 rounded-xl border border-[#2A364F]">
              <span className="text-[#F5A623] font-bold text-[11px] block">P2: Drop-in Alternatives</span>
              <span className="text-[#8B949E] text-[11px] mt-0.5 block">Migrate high-centrality utilities to modular libraries (e.g. lodash-es, jose).</span>
            </div>
            <div className="bg-[#141B26] p-3 rounded-xl border border-[#2A364F]">
              <span className="text-[#3DDC97] font-bold text-[11px] block">P3: CI/CD Build Gates</span>
              <span className="text-[#8B949E] text-[11px] mt-0.5 block">Enforce strict semver pin verification in automated build pipelines.</span>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex justify-between items-center pt-2 text-xs">
          <span className="text-[#8B949E]">Exportable CISO &amp; DevSecOps Executive Summary</span>

          <div className="flex items-center space-x-3">
            <button
              onClick={handleCopy}
              className="px-4 py-2.5 rounded-xl bg-[#1C2333] hover:bg-[#2A364F] border border-[#2A364F] text-[#E6EDF3] font-semibold flex items-center space-x-2 transition-all"
            >
              {copied ? <Check className="w-4 h-4 text-[#3DDC97]" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied' : 'Copy Brief'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="px-4 py-2.5 rounded-xl bg-[#3DDC97] text-[#0A0E14] font-bold hover:bg-[#3DDC97]/90 flex items-center space-x-2 transition-all shadow-glow-green"
            >
              <Download className="w-4 h-4" />
              <span>Download Executive Brief</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
